### ISSUE TITLE
Include Author(s) credit link?

### ISSUE THREAD

**Issue by lukeed** [riot/made-with-riot#14]
Adds a little more incentive to sharing a Riot project?

Simple block to add to the `projects.json` file:

```json
"author": {
  "name": "Luke Edwards",
  "link": "http://whatever"
}
```

Author info would display nicely inside the Details pane

**Comment by kazzkiq** [comment]
Nice idea, we can add this. Will be taking a look at it this weekend.

**Comment by kazzkiq** [comment]
Done. Now users are able to add "owner" information which is displayed right bellow URL:

<img width="399" alt="captura de tela 2016-08-06 as 03 43 57" src="https://cloud.githubusercontent.com/assets/1953194/17455190/6639eeca-5b86-11e6-9bc8-4c3b5724bf15.png">

The JSON structure to add an author to the project is:
```json
{
  "..."
  "author": {
    "name": "John Doe",
    "url": "http://optional-url.com"
  }
}
```

The URL value is optional, but owner's name is needed, otherwise it will just be ignored by the component.
