### ISSUE TITLE
Document which projects are fit to become part of this repo

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/made-with-riot#17]
Hello there!

I'd love to know what kind of content you'd like to be submitted.

Tiny apps?
Tools?
Helper?
Registration required to see it in action?

Thanks in advance!

**Comment by kazzkiq** [comment]
Hello, @MartinMuzatko.

I would say that a project must fit basically two requirements to get into showcase:

- It uses Riot;
- User can interact with it somehow.

It can be a mobile app, a website, a Github project (having a web page)... once user can interact with it (and by that I mean its not just code alone, but something actually running), and its published publicly, its good to go.


@GianlucaGuarini @prateekbh Would like to add anything?

**Comment by prateekbh** [comment]
@MartinMuzatko @kazzkiq  i guess since Riot community is still growing and the thing has not viral like jQuery or React hence we should be a lil less restrictive about whom we let showcase. If Riot is used, you are welcome. may be some are bound by geological boundaries like a countries e commerce, but we should let them post it.

Also just from the top of my mind. Should we give PWAs more importance?

P.S Web app should be intractable :)

**Comment by GianlucaGuarini** [comment]
I would just let people posting their projects and we can decide case by case whether we want to publish them or not.. I would avoid to overcomplicate the submission process

**Comment by MartinMuzatko** [comment]
Agree @GianlucaGuarini @prateekbh  and @kazzkiq  ! Closing this issue for now.
