### ISSUE TITLE
Add margin bottom to the showcases

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/made-with-riot#40]
At moment the showcases seem to be to close to each other at least on desktop
![screen shot 2016-12-19 at 08 18 30](https://cloud.githubusercontent.com/assets/879612/21304197/c35b48ae-c5c3-11e6-9f13-e98502fe15f9.png)

Adding 10/20px margin bottom would be a reasonable solution

**Comment by cognitom** [comment]
Looks like a Firefox specific issue.

![image](https://cloud.githubusercontent.com/assets/16032/21304535/2e648c06-c609-11e6-8e7c-2b21e16e0efa.png)

**Comment by kazzkiq** [comment]
It seems to be a polemic [*not-a-bug* issue](https://bugzilla.mozilla.org/show_bug.cgi?id=958714#c29) that every other browser implemented erroneously and Firefox just let it breaks as "intended" by the W3C Flexbox spec.

Basically, when using Flexbox elements without a explicit `height`, you cannot use vertical `margin` or `padding` with percentage values. If you do, they're converted to `0`. All other Browsers calculate the percentage, only Firefox converts it to `0`.

Just thought it would be interesting to share the details of this inconsistency in case anyone trip over this in the future.

The fix is simple, I will just change the percentage margin to a fixed `px` one.

**Comment by GianlucaGuarini** [comment]
@kazzkiq it's because firefox rulez
<img src="https://media.giphy.com/media/hYk5bD26SKtKU/giphy.gif"/>

btw thanks for the explanation

**Comment by kazzkiq** [comment]
I've pushed the fix to [production](http://riotjs.com/made-with-riot/).
